name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Specify the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      run: git config user.email "myameen033@gmail.com" && git config --global user.name "yameen7" && npx gh-pages -d build -r https://x-access-token:${{ secrets.GH_PAT }}@github.com/yameen7/todo.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
